### ISSUE TITLE
Clan Rank standarization

### ISSUE THREAD

**Issue by Nonemoticoner** [IDragonfire/faf.webapp#21]
Right now we need:
ACU (leader, can do everything i.e. invite, kick players, change their ranks, change details, post news)
LAB (newly invited member)

Later:
SACU (co-leader, can do everything but changing rank of ACU and editing clan details)
HAB (full member, dunno what extra power should have yet)

**Comment by IDragonfire** [comment]
This issue was moved to FAForever/faf.webapp#7
