### ISSUE TITLE
Issue with accepting member requests

### ISSUE THREAD

**Issue by Sheeo** [IDragonfire/faf.webapp#63]
On accepting member requests, people have been reporting the following issue:

```
Internal Server Error
Fatal error: Call to a member function erase() on a non-object
```

Unsure if this could be because of our server stack migration to php-fpm instead of mod_php?

**Comment by IDragonfire** [comment]
That's look like a php error ^^
What did you try to delete?

**Comment by IDragonfire** [comment]
routing was wrong

using `$args` instead of `$1`
