### ISSUE TITLE
People can't join clans

### ISSUE THREAD

**Issue by VoRGoR** [IDragonfire/faf.webapp#64]
![screen](https://cloud.githubusercontent.com/assets/8906373/5865340/9552f92e-a280-11e4-924f-9bd4416da4f0.jpg)

**Comment by IDragonfire** [comment]
What people?
All people?
All clans?

Since when?

**Comment by VoRGoR** [comment]
LTE clan
Matije_,



getting more names now, since now (they made a clan, disbanded it, now they can't join new one)

**Comment by IDragonfire** [comment]
Atm I cannot invite anybody :(

**Comment by IDragonfire** [comment]
working again ...
routing was wrong ...
